import json
import os
import requests
from fastapi import FastAPI, HTTPException, BackgroundTasks, Header, Request, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from backend.app.services.pr_parser import parse_pr_url
from backend.app.services.github_service import (
    fetch_pr_details,
    fetch_pr_files,
    post_pr_comment
)
from backend.app.services.ai_review_service import review_code_diff
import hmac
import hashlib
from sqlalchemy.orm import Session
from backend.app.database import engine, get_db
import backend.app.models as models
from backend.app.auth import encrypt_token, decrypt_token, create_jwt_token, get_current_user

# Create database tables
models.Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="AI PR Reviewer",
    description="AI-powered GitHub Pull Request Reviewer",
    version="1.0.0"
)

# Add CORS middleware to allow requests from the React frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, specify the exact frontend domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class PostReviewRequest(BaseModel):
    pr_url: str



# -----------------------------------------------------------------------
# FEATURE #1 + #2 + #3 Helper: Format per-file reviews → GitHub Markdown
#
# Updated to handle the new per-file structure with severity scoring.
# Each file gets its own section in the comment.
# Each issue shows: severity badge + description + fix suggestion
#
# Example output on GitHub:
#   ## 🤖 AI PR Review
#   ### 📊 PR Quality Score: 85 / 100
#   ### 📂 auth.py
#   🔴 CRITICAL — SQL injection via f-string → Use parameterized queries
#   🟢 LOW — Variable name x → Rename to userId
# -----------------------------------------------------------------------
def calculate_pr_score(file_reviews: list) -> int:
    score = 100
    penalties = {
        "CRITICAL": 20,
        "HIGH": 10,
        "MEDIUM": 5,
        "LOW": 1
    }
    
    for fr in file_reviews:
        review = fr.get("review", {})
        for category, items in review.items():
            if isinstance(items, list):
                for item in items:
                    sev = item.get("severity", "LOW").upper()
                    score -= penalties.get(sev, 1)
                    
    return max(0, min(100, score))

def format_review_as_comment(file_reviews: list, score: int = None) -> str:
    """Convert per-file AI reviews into a formatted GitHub markdown comment."""

    SEV_EMOJI = {
        "CRITICAL": "🔴",
        "HIGH":     "🟠",
        "MEDIUM":   "🟡",
        "LOW":      "🟢",
    }

    def section(emoji, title, items):
        if not items:
            return f"**{emoji} {title}** — ✅ No issues found  \n"
        lines = ""
        for item in items:
            sev     = item.get("severity", "LOW").upper()
            issue   = item.get("issue", "")
            suggest = item.get("suggestion", "")
            badge   = SEV_EMOJI.get(sev, "⚪")
            lines  += f"- {badge} **{sev}** — {issue}  \n"
            if suggest:
                lines += f"  > 💡 *Fix: {suggest}*  \n"
        return f"**{emoji} {title} ({len(items)})**  \n{lines}"

    comment  = "## 🤖 AI PR Review\n"
    if score is not None:
        if score >= 80:
            health = "🟢 **Good Health**"
        elif score >= 50:
            health = "🟡 **Needs Improvement**"
        else:
            health = "🔴 **Critical Issues**"
        comment += f"### 📊 PR Quality Score: **{score} / 100** ({health})\n\n"
        
    comment += "> *Automated review powered by **Groq LLaMA 3.3 70B** — per-file with severity scoring*\n\n"
    comment += "---\n\n"

    for file_review in file_reviews:
        filename = file_review.get("filename", "Unknown File")
        review   = file_review.get("review", {})
        comment += f"### 📂 `{filename}`\n\n"
        comment += section("🐞", "Bugs",                      review.get("bugs", []))
        comment += section("🔒", "Security Issues",           review.get("security_issues", []))
        comment += section("⚠️", "Edge Cases",                review.get("edge_cases", []))
        comment += section("⚡", "Optimizations",             review.get("optimizations", []))
        comment += section("🧹", "Code Quality",              review.get("code_quality_improvements", []))
        comment += "\n---\n\n"

    comment += "*🔗 Generated by [AI PR Reviewer](https://github.com)*"
    return comment


@app.get("/")
def home():
    return {
        "status": "success",
        "message": "AI PR Reviewer backend is running"
    }

class GitHubLoginRequest(BaseModel):
    code: str

@app.post("/auth/github")
def github_login(req: GitHubLoginRequest, db: Session = Depends(get_db)):
    # 1. Exchange 'code' for a GitHub Access Token
    token_url = "https://github.com/login/oauth/access_token"
    payload = {
        "client_id": os.getenv("GITHUB_CLIENT_ID"),
        "client_secret": os.getenv("GITHUB_CLIENT_SECRET"),
        "code": req.code
    }
    headers = {"Accept": "application/json"}
    token_res = requests.post(token_url, json=payload, headers=headers).json()
    access_token = token_res.get("access_token")

    if not access_token:
        raise HTTPException(status_code=400, detail="Failed to obtain access token from GitHub")

    # 2. Fetch the user's GitHub profile
    user_res = requests.get("https://api.github.com/user", 
                            headers={"Authorization": f"Bearer {access_token}"}).json()
    
    # 3. Save or update the user in your database
    user = db.query(models.User).filter(models.User.github_id == user_res.get("id")).first()
    if not user:
        user = models.User(
            github_id=user_res.get("id"), 
            username=user_res.get("login"),
            avatar_url=user_res.get("avatar_url"),
            encrypted_github_token=encrypt_token(access_token)
        )
        db.add(user)
    else:
        user.username = user_res.get("login")
        user.avatar_url = user_res.get("avatar_url")
        user.encrypted_github_token = encrypt_token(access_token)
        
    db.commit()
    db.refresh(user)

    # 4. Generate a JWT for your own app's session
    app_token = create_jwt_token({"user_id": user.id})
    return {
        "token": app_token, 
        "username": user.username,
        "avatar_url": user.avatar_url
    }

@app.get("/pr-details")
def get_pr_details(pr_url: str):
    try:
        parsed_data = parse_pr_url(pr_url)
        pr_details = fetch_pr_details(
            parsed_data["owner"],
            parsed_data["repo"],
            parsed_data["pull_number"]
        )
        return {
            "success": True,
            "data": pr_details
        }
    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )

# -----------------------------------------------------------------------
# FEATURE #2 + #3: Updated /ai-review — Per-File with Severity Scoring
#
# OLD: Combined all files → one prompt → one flat JSON
# NEW: Each file → own prompt → list of per-file reviews with severity
#
# Returns:
#   {
#     "success": true,
#     "files_reviewed": 3,
#     "reviews": [
#       {
#         "filename": "auth.py",
#         "additions": 12,
#         "deletions": 3,
#         "review": {
#           "bugs": [{"issue": "...", "severity": "CRITICAL", "suggestion": "..."}],
#           "security_issues": [...], ...
#         }
#       },
#       ...
#     ]
#   }
# -----------------------------------------------------------------------
@app.get("/ai-review")
def ai_review(pr_url: str):

    try:
        parsed_data = parse_pr_url(pr_url)

        files = fetch_pr_files(
            parsed_data["owner"],
            parsed_data["repo"],
            parsed_data["pull_number"]
        )

        file_reviews = []

        for file in files:
            patch = file.get("patch")
            if not patch:
                # Skip files with no diff (e.g. binary files, renames)
                continue

            filename    = file.get("filename", "unknown")
            review_text = review_code_diff(filename, patch)

            try:
                review_json = json.loads(review_text)
            except json.JSONDecodeError:
                review_json = {}

            file_reviews.append({
                "filename":  filename,
                "status":    file.get("status", "modified"),
                "additions": file.get("additions", 0),
                "deletions": file.get("deletions", 0),
                "review":    review_json
            })

        score = calculate_pr_score(file_reviews)

        return {
            "success":       True,
            "files_reviewed": len(file_reviews),
            "score":         score,
            "reviews":       file_reviews
        }

    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )


# -----------------------------------------------------------------------
# FEATURE #1 Endpoint: POST /post-review
#
# Flow:
#   1. Parse the PR URL  →  get owner, repo, pull_number
#   2. Fetch changed files from GitHub API (with token if provided)
#   3. Run AI review on the combined code diff
#   4. Format the review JSON → nice GitHub Markdown string
#   5. POST that string to GitHub as a comment on the PR
#   6. Return the direct URL to the posted comment
#
# Query params:
#   pr_url       : Full GitHub PR URL
#   github_token : GitHub Personal Access Token (PAT) with repo scope
# -----------------------------------------------------------------------
@app.post("/post-review")
def post_review_to_github(req: PostReviewRequest, db: Session = Depends(get_db), current_user: models.User = Depends(get_current_user)):
    pr_url = req.pr_url
    github_token = decrypt_token(current_user.encrypted_github_token)

    try:
        # Step 1: Parse the PR URL
        parsed_data = parse_pr_url(pr_url)
        owner       = parsed_data["owner"]
        repo        = parsed_data["repo"]
        pull_number = parsed_data["pull_number"]

        # Step 2: Fetch changed files (token passed for private repos)
        files = fetch_pr_files(owner, repo, pull_number, github_token)

        # Step 3: Review each file individually (per-file feature)
        file_reviews = []
        for file in files:
            patch = file.get("patch")
            if not patch:
                continue
            filename    = file.get("filename", "unknown")
            review_text = review_code_diff(filename, patch)
            try:
                review_json = json.loads(review_text)
            except json.JSONDecodeError:
                review_json = {}
            file_reviews.append({
                "filename": filename,
                "review":   review_json
            })

        # Step 4: Format per-file reviews → GitHub Markdown with severity
        score = calculate_pr_score(file_reviews)
        comment_body = format_review_as_comment(file_reviews, score)

        # Step 5: Post comment to GitHub
        comment_url = post_pr_comment(
            owner, repo, pull_number, comment_body, github_token
        )

        # Step 6: Save to PostgreSQL Analytics Database
        try:
            db_record = models.ReviewHistory(
                pr_url=pr_url,
                repo=repo,
                owner=owner,
                pr_score=score,
                files_reviewed=len(file_reviews),
                reviews_json=file_reviews,
                user_id=current_user.id
            )
            db.add(db_record)
            db.commit()
        except Exception as e:
            print(f"Failed to save analytics to DB: {e}")

        return {
            "success":     True,
            "message":     "Review posted successfully to GitHub!",
            "comment_url": comment_url
        }

    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail=str(e)
        )


# -----------------------------------------------------------------------
# FEATURE #5: Webhook Endpoint (Auto-Review on New PR)
#
# Listens for GitHub pull_request events and processes them in the background.
# -----------------------------------------------------------------------

# Dummy secret for demonstration. In production, store this in a DB per user.
WEBHOOK_SECRET = "sk_web_987654321"

def process_webhook_pr(pr_url: str, github_token: str):
    """Background task to review a PR triggered by a webhook."""
    try:
        parsed_data = parse_pr_url(pr_url)
        owner = parsed_data["owner"]
        repo = parsed_data["repo"]
        pull_number = parsed_data["pull_number"]

        files = fetch_pr_files(owner, repo, pull_number, github_token)

        file_reviews = []
        for file in files:
            patch = file.get("patch")
            if not patch:
                continue
            filename = file.get("filename", "unknown")
            review_text = review_code_diff(filename, patch)
            try:
                review_json = json.loads(review_text)
            except json.JSONDecodeError:
                review_json = {}
            file_reviews.append({
                "filename": filename,
                "review": review_json
            })

        score = calculate_pr_score(file_reviews)
        comment_body = format_review_as_comment(file_reviews, score)
        
        post_pr_comment(owner, repo, pull_number, comment_body, github_token)
        print(f"✅ Webhook review successfully posted for {pr_url} with score {score}")

        # Save to PostgreSQL Analytics Database
        try:
            db = next(get_db())
            db_record = models.ReviewHistory(
                pr_url=pr_url,
                repo=repo,
                owner=owner,
                pr_score=score,
                files_reviewed=len(file_reviews),
                reviews_json=file_reviews
            )
            db.add(db_record)
            db.commit()
            db.close()
        except Exception as e:
            print(f"Failed to save webhook analytics to DB: {e}")

    except Exception as e:
        print(f"❌ Webhook review failed for {pr_url}: {e}")

@app.post("/webhook/{user_id}")
async def github_webhook(
    user_id: str,
    request: Request,
    background_tasks: BackgroundTasks,
    x_hub_signature_256: str = Header(None),
    x_github_event: str = Header(None)
):
    # 1. Verify Signature
    if not x_hub_signature_256:
        raise HTTPException(status_code=401, detail="Missing signature")
    
    payload = await request.body()
    signature = hmac.new(WEBHOOK_SECRET.encode(), payload, hashlib.sha256).hexdigest()
    expected_signature = f"sha256={signature}"
    
    if not hmac.compare_digest(x_hub_signature_256, expected_signature):
        # Allow bypassing for local testing if signature is "test"
        if x_hub_signature_256 != "test":
            raise HTTPException(status_code=401, detail="Invalid signature")

    # 2. Filter Events
    if x_github_event != "pull_request":
        return {"status": "ignored", "reason": "Not a pull_request event"}
        
    try:
        data = json.loads(payload)
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="Invalid JSON payload")

    action = data.get("action")
    if action not in ["opened", "synchronize"]:
        return {"status": "ignored", "reason": f"Action '{action}' ignored"}

    pr_url = data.get("pull_request", {}).get("html_url")
    if not pr_url:
        return {"status": "ignored", "reason": "No PR URL in payload"}

    # In a real app, you would look up the user's saved GitHub Token from a DB.
    # We will assume it's passed or available. For now, we use a placeholder or empty string
    # assuming the repo is public if no token is available.
    # Or for this test, we can just pass an empty string (works for public repos).
    user_github_token = "" 

    # 3. Process in Background
    background_tasks.add_task(process_webhook_pr, pr_url, user_github_token)

    return {"status": "accepted", "message": f"Review queued for {pr_url}"}


# -----------------------------------------------------------------------
# FEATURE #7: Analytics Dashboard Endpoint
# -----------------------------------------------------------------------
@app.get("/analytics/{owner}/{repo}")
def get_repo_analytics(owner: str, repo: str, db: Session = Depends(get_db)):
    """Fetch historical analytics for a specific repository."""
    records = db.query(models.ReviewHistory).filter(
        models.ReviewHistory.owner == owner,
        models.ReviewHistory.repo == repo
    ).order_by(models.ReviewHistory.created_at.desc()).limit(50).all()

    total_reviews = len(records)
    avg_score = sum(r.pr_score for r in records if r.pr_score is not None) / total_reviews if total_reviews > 0 else 0

    return {
        "success": True,
        "owner": owner,
        "repo": repo,
        "total_reviews": total_reviews,
        "average_score": round(avg_score, 1),
        "history": [
            {
                "id": r.id,
                "pr_url": r.pr_url,
                "pr_score": r.pr_score,
                "files_reviewed": r.files_reviewed,
                "created_at": r.created_at
            } for r in records
        ]
    }