"""
File: models.py

Purpose:
Defines the database schema and models using SQLAlchemy ORM.

Responsibilities:
- Map python classes User and ReviewHistory to SQL tables.
- Define columns, constraint keys, data types, indexes, and default values.
- Establish relationships between User and ReviewHistory objects (one-to-many relationship).

Dependencies:
- sqlalchemy
- database.py
"""

from sqlalchemy import Column, Integer, String, DateTime, JSON, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .database import Base

class User(Base):
    """
    Represents an authenticated GitHub User within the system.

    Why:
    Maintains persistent record of authorized users, their settings, and cryptographic 
    GitHub OAuth access tokens so the application can communicate with GitHub on their behalf.

    Fields:
        id (Integer): Primary key.
        github_id (Integer): The user's unique numeric GitHub identifier.
        username (String): User's GitHub handle/username.
        avatar_url (String): GitHub profile image URL.
        encrypted_github_token (String): Cryptographically protected GitHub OAuth access token.
        reviews (relationship): One-to-many link to review histories generated by this user.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    github_id = Column(Integer, unique=True, index=True, nullable=False)
    username = Column(String, unique=True, nullable=False)
    avatar_url = Column(String, nullable=True)
    encrypted_github_token = Column(String, nullable=False)
    
    # Establishes one-to-many relationship with ReviewHistory objects
    reviews = relationship("ReviewHistory", back_populates="user")

class ReviewHistory(Base):
    """
    Represents a historical log of an AI Pull Request review.

    Why:
    Persists review summaries, scores, and files reviewed, allowing users to query, 
    filter, and retrieve their historical PR reviews on the Dashboard or History panel.

    Fields:
        id (Integer): Primary key.
        pr_url (String): Full URL of the reviewed Pull Request.
        repo (String): Name of the repository where the PR belongs.
        owner (String): GitHub owner/organization of the repository.
        pr_score (Integer): Calculated score or rating of the PR code quality.
        files_reviewed (Integer): Total number of files checked during review.
        reviews_json (JSON): Structured payload of findings, recommendations, and files analysis.
        created_at (DateTime): Timestamp of review generation.
        user_id (Integer): Foreign key referencing the users table (nullable to support legacy entries).
        user (relationship): Many-to-one link back to the User model.
    """
    __tablename__ = "review_history"

    id = Column(Integer, primary_key=True, index=True)
    pr_url = Column(String, index=True, nullable=False)
    repo = Column(String, index=True, nullable=False)
    owner = Column(String, index=True, nullable=False)
    pr_score = Column(Integer, nullable=True)
    files_reviewed = Column(Integer, default=0)
    reviews_json = Column(JSON, nullable=False)  # Stores the actual review content
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Establish foreign key link to User. Nullable to prevent crashing with legacy records.
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    user = relationship("User", back_populates="reviews")

