/**
 * File: exportUtils.js
 *
 * Purpose:
 * Exports code review report payloads in Markdown and PDF printer-friendly formats.
 *
 * Responsibilities:
 * - Build markdown text reports detailing review sessions and file violations.
 * - Inject styles and layout nodes (HTML wrapper) to convert raw reports into PDF view layouts.
 * - Manage trigger downloads in browsers using standard anchor triggers and RevokeObjectURL.
 *
 * Dependencies:
 * - REVIEW_SECTIONS (utils/constants)
 */

import { REVIEW_SECTIONS } from './constants'

// Severity level color codes for markdown reports representation
const SEV_EMOJI = { CRITICAL: '🔴', HIGH: '🟠', MEDIUM: '🟡', LOW: '🟢' }

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Formats a single review section block (e.g. Bugs) in Markdown.
 *
 * @param {string} emoji - Category icon.
 * @param {string} title - Category display name.
 * @param {array} items - List of issues in category.
 * @returns {string} Formatted markdown block.
 */
function sectionBlock(emoji, title, items) {
  if (!items || items.length === 0)
    return `**${emoji} ${title}** — ✅ No issues found\n\n`

  let block = `**${emoji} ${title} (${items.length})**\n\n`
  for (const item of items) {
    if (typeof item === 'string') {
      block += `- ${item}\n`
      continue
    }
    const sev   = (item.severity || 'LOW').toUpperCase()
    const badge = SEV_EMOJI[sev] || '⚪'
    block += `- ${badge} **${sev}** — ${item.issue}\n`
    if (item.suggestion) block += `  > 💡 *Fix: ${item.suggestion}*\n`
  }
  return block + '\n'
}

// ── Markdown Generator ─────────────────────────────────────────────────────

/**
 * Generate a full Markdown report from a completed review.
 *
 * Why:
 * Compiles a formatted text review detailing PR changes and AI comments.
 *
 * @param {object|null} prDetails - Metadata details of the reviewed Pull Request.
 * @param {array} reviews - Set of file reviews.
 * @param {string} prUrl - Full GitHub PR link.
 * @returns {string} Fully compiled markdown report.
 */
export function generateMarkdown(prDetails, reviews, prUrl = '') {
  const now = new Date().toLocaleString()

  let md = `# 🤖 AI PR Review Report\n\n`
  md += `> Generated by **AI PR Reviewer** · ${now}\n\n`
  md += `---\n\n`

  // Compile PR metadata details table if details exist
  if (prDetails) {
    md += `## 📌 Pull Request Details\n\n`
    md += `| Field | Value |\n|-------|-------|\n`
    md += `| **URL** | ${prUrl} |\n`
    md += `| **Title** | ${prDetails.title || 'N/A'} |\n`
    md += `| **Author** | ${prDetails.author || 'N/A'} |\n`
    md += `| **State** | ${(prDetails.state || 'N/A').toUpperCase()} |\n`
    md += `| **Changed Files** | ${prDetails.changed_files ?? '—'} |\n\n`
    md += `---\n\n`
  }

  // Iterate and compile per-file reviews markdown blocks
  md += `## 🧠 AI Review\n\n`
  md += `**${reviews.length} file${reviews.length !== 1 ? 's' : ''} analysed**\n\n`

  for (const fr of reviews) {
    const totalIssues = REVIEW_SECTIONS.reduce(
      (acc, s) => acc + (fr.review?.[s.key]?.length || 0), 0
    )
    const badge = totalIssues > 0 ? `🔴 ${totalIssues} issue(s)` : '✅ Clean'

    md += `### 📄 \`${fr.filename}\`  \`+${fr.additions || 0} / -${fr.deletions || 0}\`  —  ${badge}\n\n`

    for (const s of REVIEW_SECTIONS) {
      md += sectionBlock(s.emoji, s.title, fr.review?.[s.key] || [])
    }

    md += `---\n\n`
  }

  md += `*🔗 Generated by [AI PR Reviewer](https://github.com)*\n`
  return md
}

// ── Download helpers ───────────────────────────────────────────────────────

/**
 * Trigger a browser download of a Markdown file.
 *
 * Why:
 * Downloads the completed review report locally as a Markdown file.
 *
 * @param {object|null} prDetails - PR metadata.
 * @param {array} reviews - File review logs.
 * @param {string} prUrl - Full GitHub PR link.
 */
export function downloadMarkdown(prDetails, reviews, prUrl) {
  const content  = generateMarkdown(prDetails, reviews, prUrl)
  const filename = `pr-review-${Date.now()}.md`
  triggerDownload(content, filename, 'text/markdown')
}

/**
 * Open a print-optimised HTML window and trigger the browser print dialog
 * (user can Save as PDF from there).
 *
 * Why:
 * Opens print preview menus so users can convert the report directly to PDF.
 *
 * @param {object|null} prDetails - PR metadata.
 * @param {array} reviews - File review logs.
 * @param {string} prUrl - Full GitHub PR link.
 */
export function downloadPDF(prDetails, reviews, prUrl) {
  const md = generateMarkdown(prDetails, reviews, prUrl)

  // Convert markdown elements to simple printable HTML nodes using regex replacements
  const htmlBody = md
    .replace(/^#{1} (.+)$/gm,  '<h1>$1</h1>')
    .replace(/^#{2} (.+)$/gm,  '<h2>$1</h2>')
    .replace(/^#{3} (.+)$/gm,  '<h3>$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g,     '<em>$1</em>')
    .replace(/`(.+?)`/g,       '<code>$1</code>')
    .replace(/^> (.+)$/gm,     '<blockquote>$1</blockquote>')
    .replace(/^- (.+)$/gm,     '<li>$1</li>')
    .replace(/^---$/gm,        '<hr/>')
    .replace(/\n/g,            '<br/>')

  const win = window.open('', '_blank')
  win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>PR Review Report</title>
  <style>
    body  { font-family: 'Segoe UI', sans-serif; max-width: 860px; margin: 40px auto; color: #1a1a2e; font-size: 14px; line-height: 1.7; }
    h1    { color: #6d28d9; border-bottom: 2px solid #6d28d9; padding-bottom: 8px; }
    h2    { color: #4c1d95; margin-top: 2em; }
    h3    { color: #1e1b4b; font-family: monospace; background: #f0f0ff; padding: 6px 10px; border-radius: 6px; }
    code  { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 12px; }
    blockquote { border-left: 3px solid #8b5cf6; margin: 8px 0; padding: 4px 12px; background: #f5f3ff; color: #555; }
    hr    { border: none; border-top: 1px solid #e5e7eb; margin: 16px 0; }
    li    { margin: 4px 0; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 16px; }
    th,td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; }
    th    { background: #f5f3ff; color: #4c1d95; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>${htmlBody}</body>
</html>`)
  win.document.close()
  setTimeout(() => { win.print() }, 300)
}

// ── Internal util ──────────────────────────────────────────────────────────

/**
 * Triggers a document anchor download of blob content in browsers.
 *
 * @param {string} content - Text file content data.
 * @param {string} filename - Output name of the downloaded file.
 * @param {string} mimeType - File type MIME indicator.
 */
function triggerDownload(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
